README.md, application/base/main/default/classes/Constants.cls-meta.xml, application/base/main/default/classes/MetadataTriggerHandler.cls-meta.xml, application/base/main/default/classes/MetadataTriggerHandlerTest.cls, application/base/main/default/classes/MetadataTriggerHandlerTest.cls-meta.xml, application/base/main/default/classes/TestUtility.cls-meta.xml, application/base/main/default/classes/TriggerAction.cls-meta.xml, application/base/main/default/classes/TriggerBaseTest.cls-meta.xml, application/base/main/default/triggers/OpportunityTrigger.trigger-meta.xml, application/opportunity-automation/main/default/classes/ta_Opportunity_StageChangeRules.cls-meta.xml, application/opportunity-automation/main/default/classes/ta_Opportunity_StageChangeRulesTest.cls, application/opportunity-automation/main/default/classes/ta_Opportunity_StageChangeRulesTest.cls-meta.xml, application/opportunity-automation/main/default/classes/ta_Opportunity_StageInsertRules.cls-meta.xml, application/opportunity-automation/main/default/classes/ta_Opportunity_StageInsertRulesTest.cls, application/opportunity-automation/main/default/classes/ta_Opportunity_StageInsertRulesTest.cls-meta.xml, application/opportunity-automation/main/default/classes/ta_Opportunity_YugeDeal.cls-meta.xml, application/opportunity-automation/main/default/classes/ta_Opportunity_YugeDealTest.cls-meta.xml, sfdx-project.json
Fixes #1 
A few things to note:
- I followed the advice in the Contributing.md and filled out my CLA
- There's an unusual amount of whitespace in each file. I'm not sure if this is intended or not, but I had to make my changes in Notepad because even with VS Code's "Format On Save" option turned off (and with Prettier disabled, as well as the VS Code settings related to trimming whitespace), my original diff was still misrepresented as a total file rewrite :(
- At least on the generated diff prior to submitting the PR, I am being told that `application/opportunity-automation/main/default/customMetadata/Trigger_Action.ta_Opportunity_SendWonNotification.md-meta.xml` has been deleted, though this was not part of any `git diff` I saw prior to committing and pushing. Not sure what that's about …
=> Winter 21 changes

README.md, application/base/main/default/classes/Constants.cls, application/base/main/default/classes/MetadataTriggerHandler.cls, application/base/main/default/classes/MetadataTriggerHandlerTest.cls, application/base/main/default/classes/TestUtility.cls, application/base/main/default/classes/TriggerAction.cls, application/base/main/default/classes/TriggerBase.cls, application/base/main/default/classes/TriggerBaseTest.cls, application/opportunity-automation/main/default/classes/ta_Opportunity_StageChangeRules.cls, application/opportunity-automation/main/default/classes/ta_Opportunity_StageChangeRulesTest.cls, application/opportunity-automation/main/default/classes/ta_Opportunity_StageInsertRules.cls, application/opportunity-automation/main/default/classes/ta_Opportunity_StageInsertRulesTest.cls, application/opportunity-automation/main/default/classes/ta_Opportunity_YugeDeal.cls, application/opportunity-automation/main/default/classes/ta_Opportunity_YugeDealTest.cls
Cleaned up formatting issues and moved the `addError()` to the TriggerBase
=> Metadata trigger handler formatting

README.md, application/base/main/default/classes/MetadataTriggerHandler.cls, application/base/main/default/classes/TriggerBase.cls
Fixed before insert missing try/catch and separated Type Exception handling form NullPointer Exception handling
=> Fixing before insert

application/base/main/default/objects/Trigger_Action__mdt/fields/Order__c.field-meta.xml
Increased order precision to facilitate working in teams
=> Increase order precision for teams.

application/base/main/default/classes/MetadataTriggerHandler.cls, application/base/main/default/classes/MetadataTriggerHandlerTest.cls
Fixed improper formatting of invalid class error in MetadataTriggerHandler.
=> consolidate exception handling

README.md, application/opportunity-automation/main/default/classes/ta_Opportunity_YugeDeal.cls
Fixing whitespace and readme
> It's a good idea to open an issue first for discussion.
=> Fixing whitespace and readme

README.md, application/base/main/default/classes/MetadataTriggerHandler.cls, application/base/main/default/classes/MetadataTriggerHandlerTest.cls, application/base/main/default/layouts/Trigger_Action__mdt-Trigger Action Layout.layout-meta.xml, application/base/main/default/layouts/sObject_Trigger_Setting__mdt-sObject Trigger Setting Layout.layout-meta.xml, application/base/main/default/objects/Trigger_Action__mdt/fields/Bypass_Permission__c.field-meta.xml, application/base/main/default/objects/Trigger_Action__mdt/fields/Required_Permission__c.field-meta.xml, application/base/main/default/objects/sObject_Trigger_Setting__mdt/fields/Bypass_Permission__c.field-meta.xml, application/base/main/default/objects/sObject_Trigger_Setting__mdt/fields/Required_Permission__c.field-meta.xml
Added support to specify "Bypass" and "Required" permissions.
- [ x] Tests pass
- [ x] Appropriate changes to README are included in PR
=> Adding in "Bypass" and "Required" permission functionality.

trigger-actions-framework/main/default/classes/MetadataTriggerHandler.cls
Fixes #29 by appropriately checking for bypasses at the action level.
=> Fix issues with action bypass

trigger-actions-framework/main/default/classes/MetadataTriggerHandler.cls
Fixing object level apex bypass
=> Fix bypass

README.md, trigger-actions-framework/main/default/classes/MetadataTriggerHandler.cls, trigger-actions-framework/main/default/classes/TriggerActionFlow.cls, trigger-actions-framework/main/default/layouts/Trigger_Action__mdt-Trigger Action Layout.layout-meta.xml, trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/Allow_Flow_Recursion__c.field-meta.xml, trigger-actions-framework/main/default/objects/Trigger_Action__mdt/validationRules/Must_Choose_A_Context.validationRule-meta.xml, trigger-actions-framework/main/default/objects/Trigger_Action__mdt/validationRules/Only_One_Context.validationRule-meta.xml, trigger-actions-framework/main/default/objects/Trigger_Action__mdt/validationRules/Recursion_Only_For_Flows.validationRule-meta.xml
Allow for the admins/developers to enable a flow to execute recursively.
=> Allow users to enable recursive flows.

README.md, trigger-actions-framework/main/default/classes/MetadataTriggerHandlerTest.cls, trigger-actions-framework/main/default/classes/TriggerActionFlow.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowTest.cls, trigger-actions-framework/main/default/classes/TriggerBaseTest.cls
Fixes duplicate variable use in test classes
=> clean up variables in tests and readme

README.md, trigger-actions-framework/main/default/objects/sObject_Trigger_Setting__mdt/fields/Object_API_Name__c.field-meta.xml
Updating the Readme and Field Help/Description to better explain how to use the framework with objects from installed packages.
=> Explain Support for Third Party Objects

README.md, trigger-actions-framework/main/default/classes/FlowTriggerRecord.cls, trigger-actions-framework/main/default/classes/FlowTriggerRecordTest.cls, trigger-actions-framework/main/default/classes/MetadataTriggerHandler.cls, trigger-actions-framework/main/default/classes/MetadataTriggerHandlerTest.cls, trigger-actions-framework/main/default/classes/TriggerActionFlow.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowAddError.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowAddErrorTest.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowBypass.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowBypassTest.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowClearAllBypasses.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowClearAllBypassesTest.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowClearBypass.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowClearBypassTest.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowIsBypassed.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowIsBypassedTest.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowTest.cls, trigger-actions-framework/main/default/classes/TriggerBase.cls, trigger-actions-framework/main/default/classes/TriggerBaseTest.cls
- Clean up all tests
- Add more descriptive test names
- Remove any ambiguity in access modifiers
- Remove unnecessary Test.start and Test.stop statements
- Fix erroneous date in new classes
=> 🧹 Clean up  🧹

trigger-actions-framework/main/default/classes/FlowTriggerRecord.cls-meta.xml, trigger-actions-framework/main/default/classes/FlowTriggerRecordTest.cls-meta.xml, trigger-actions-framework/main/default/classes/MetadataTriggerHandler.cls, trigger-actions-framework/main/default/classes/MetadataTriggerHandler.cls-meta.xml, trigger-actions-framework/main/default/classes/MetadataTriggerHandlerTest.cls, trigger-actions-framework/main/default/classes/MetadataTriggerHandlerTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TestUtility.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerAction.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlow.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowAddError.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowAddErrorTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowBypass.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowBypassTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowClearAllBypasses.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowClearAllBypassesTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowClearBypass.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowClearBypassTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowIsBypassed.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowIsBypassedTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerBaseTest.cls, trigger-actions-framework/main/default/classes/TriggerBaseTest.cls-meta.xml, trigger-actions-framework/main/default/flows/TriggerActionFlowTest.flow-meta.xml
- Fix MetadataTriggerHandler sharing
- Clean up tests
- Bump API version
Fixes #69
=> Fix Sharing

sfdx-project.json, trigger-actions-framework/main/default/classes/FlowTriggerRecord.cls-meta.xml, trigger-actions-framework/main/default/classes/FlowTriggerRecordTest.cls-meta.xml, trigger-actions-framework/main/default/classes/MetadataTriggerHandler.cls-meta.xml, trigger-actions-framework/main/default/classes/MetadataTriggerHandlerTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TestUtility.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerAction.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlow.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowAddError.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowAddErrorTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowBypass.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowBypassTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowClearAllBypasses.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowClearAllBypassesTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowClearBypass.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowClearBypassTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowIsBypassed.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowIsBypassedTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerBase.cls, trigger-actions-framework/main/default/classes/TriggerBase.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerBaseTest.cls-meta.xml, trigger-actions-framework/main/default/flows/TriggerActionFlowTest.flow-meta.xml
- Bump API Versions to 54
-Consistent spacing in Copyright notice
Fixes #73
=> API Version Bump

.github/workflows/CI.yml
Create a new Continuous Integration workflow.
=> Continuous Integration

.github/workflows/CI.yml
Delete Scratch Org after Tests are executed during CI job.
=> Delete Scratch Org after Tests

.github/workflows/CI.yml
=> Run CI on PR Edit

README.md, sfdx-project.json
Enable unlocked package installation
=> Unlocked Package

.github/workflows/CI.yml
Runs [sfdx-scan-pull-request](https://github.com/mitchspano/sfdx-scan-pull-request) action on PRs
=> sfdx scan pull request

README.md, sfdx-project.json
=> Update Package Version

.github/workflows/CI.yml
Update to the latest build of https://github.com/mitchspano/sfdx-scan-pull-request to support PRs initiated from a forked repository.
=> Update to Latest Scanner Action

README.md, sfdx-project.json, trigger-actions-framework/main/default/classes/TriggerActionFlow.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowTest.cls
- Fixes #101 by skipping flow invocation if there are no records to invoke
=> List index out of bounds - `Allow_Flow_Recursion__c`

README.md, sfdx-project.json, trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/Flow_Name__c.field-meta.xml
=> Fix Help Text on Flow_Name__c

trigger-actions-framework/main/default/classes/TriggerBase.cls
> It's a good idea to open an issue first for discussion.
=> Refactored how update counts are tracked

.github/workflows/CI.yml, README.md, sfdx-project.json
=> Update package version + Github Action version

.github/workflows/CI.yml
Update CI script to use sfdx alias
=> Introduce sfdx alias

.github/workflows/CI.yml
CI action execution with global installation of sfdx instead of alias
=> Install sfdx globally

.github/workflows/CI.yml
Testing updates to the sf CLI to use v2
=> Update to sf (v2) CLI

README.md, sfdx-project.json
=> Remove package version with sample components

README.md, sfdx-project.json, trigger-actions-framework/main/default/classes/FinalizerHandlerTest.cls
=> Fix test error for existing orgs with validation rules on Account

README.md, sfdx-project.json, trigger-actions-framework/main/default/classes/FlowChangeEventHeader.cls, trigger-actions-framework/main/default/classes/FlowChangeEventHeader.cls-meta.xml, trigger-actions-framework/main/default/classes/FlowChangeEventHeaderTest.cls, trigger-actions-framework/main/default/classes/FlowChangeEventHeaderTest.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlow.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowChangeEvent.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowChangeEvent.cls-meta.xml, trigger-actions-framework/main/default/classes/TriggerActionFlowChangeEventTest.cls, trigger-actions-framework/main/default/classes/TriggerActionFlowChangeEventTest.cls-meta.xml, trigger-actions-framework/main/default/objects/Trigger_Action__mdt/validationRules/Flow_Name.validationRule-meta.xml
Enables Flows to be used when processing Change Data Capture events
=> Flow change event

README.md, sfdx-project.json, trigger-actions-framework/main/default/classes/FormulaFilter.cls, trigger-actions-framework/main/default/classes/FormulaFilterTest.cls, trigger-actions-framework/main/default/classes/MetadataTriggerHandler.cls, trigger-actions-framework/main/default/classes/TriggerAction.cls
Fixes #160
Adds detailed error messages for invalid formulas and refactors `MetadataTriggerHandler` for better readability and maintainability.
=> Improve `FormulaFilter` error handling and refactor `MetadataTriggerHandler`

.prettierrc, sfdx-project.json, trigger-actions-framework/main/default/classes/MetadataTriggerHandler.cls
Fix the order of declaration and make the method easier to understand.
Fixes #163
=> Simplify the check for permission based bypass.

README.md, sfdx-project.json, trigger-actions-framework/main/default/classes/MetadataTriggerHandlerTest.cls
=> Improve to 100% coverage

.github/workflows/Package.yml
Enables the package version creation manually via invocation of the workflow
=> Generate package version workflow
